version: "3.8"
services:
  web:
    build:
      context: .
      target: development
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
      - tmp-data:/rails/tmp
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s

  redis:
    image: redis:7
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: .
      target: development
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
      - tmp-data:/rails/tmp
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  tmp-data:
